docs: remove tox from contributing docs
21cmfast/21cmFAST pull request #258
Opened 2021-10-15 19:54 UTC by steven-murray

This removes references to `tox` from the contributing docs, since they're outdated.

I'd be keen to hear from @andreimesinger if this updated instructions work well.

2021-10-19 02:27 UTC, BradGreig commented
Hey @steven-murray, realistically I will not realistically have the time to look at this for at least 3 weeks. Really sorry, just got a bunch of stuff coming up (plus a week off). Hopefully @qyx268 will have the time?

2021-10-19 04:04 UTC, steven-murray commented
> Hey @steven-murray, realistically I will not realistically have the time to look at this for at least 3 weeks. Really sorry, just got a bunch of stuff coming up (plus a week off). Hopefully @qyx268 will have the time?

No problem, thanks for letting me know, @BradGreig !

Thanks @qyx268 .

2021-11-05 13:07 UTC, qyx268 commented
this one should be closed

2021-11-05 15:56 UTC, andreimesinger commented on .github/workflows/test_suite.yaml
> +      CC: gcc
so for me, this wouldn't have worked... i couldn't get the OS to allow me to alias gcc to the non-clang version.  It is seems hardcoded to point to /usr/bin/gcc.  So I had to install by pre-pending the homebrew compiler version, i.e. gcc-11 that is in /usr/local/bin:

$ which gcc
/usr/bin/gcc
$ which gcc-11
/usr/local/bin/gcc-11

$ gcc --version
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/4.2.1
Apple clang version 13.0.0 (clang-1300.0.29.3)
Target: x86_64-apple-darwin20.6.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

$ gcc-11 --version
gcc-11 (Homebrew GCC 11.2.0) 11.2.0
Copyright (C) 2021 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

2021-11-05 16:04 UTC, andreimesinger requested changes
as i noted, for me i had to use CC=gcc-11.  CC=gcc doesn't work.

also i recommend adding an example when you say "prepend" the installation pip install with the LIB, INC, CFLAGS paths, because I didn't know the order of the paths.  so just saying something like, "e.g. $ CC=gcc-11 CFLAGS="-isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX11.3.sdk" pip install -e .[dev] "

2021-11-05 16:51 UTC, steven-murray commented
Thanks @andreimesinger, I'll add that. Why MacOS has to be be so difficult, I don't know.

2021-11-06 17:44 UTC, andreimesinger approved these changes

2021-11-06 17:44 UTC, merged